# Oauth client configuration specifics
config:
  clientID: "oauth2-proxy"
  clientSecret: "5281ace5-14b7-420f-a9b4-6057acf6821b"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: bldJNzlXVGpraVZIVlRoUjhaRURKUFBTR09oWDE2OTA=
  configFile: |-
    provider = "oidc"
    provider_display_name = "Keycloak"
    oidc_issuer_url = "https://sso.ssotest.nimb.us.eu.org/auth/realms/home"
    email_domains = [ "*" ]
    scope = "openid profile email"
    cookie_domain = ".ssotest.nimb.us.eu.org"
    whitelist_domains = ".ssotest.nimb.us.eu.org"
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    cookie_refresh = "1m"
    cookie_expire = "30m"

ingress:
  enabled: true
  path: /
  hosts:
    - oauth.ssotest.nimb.us.eu.org
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  tls:
    - secretName: oauth-proxy-tls
      hosts:
        - oauth.ssotest.nimb.us.eu.org
