---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /doduo/system-data/kubernetes
    server: doduo
  persistentVolumeReclaimPolicy: Recycle
