apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      # use IP range before authoratative DHCP server range (192.168.1.100-192.168.1.200)
      - 192.168.1.90-192.168.1.99
